package com.model.pojo;
// Generated Oct 17, 2020 10:58:01 PM by Hibernate Tools 4.3.1

import com.DAO.DAOOrders;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;




/**
 * Orders generated by hbm2java
 */
@ManagedBean
@RequestScoped
public class Orders  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private String name;
     private String productName;
     private Integer idObat;
     private String address;
     private Long price;

    public Orders() {
    }

	
    public Orders(Product product, String name) {
        this.product = product;
        this.name = name;
    }
    public Orders(Product product, String name, String productName, String address, Long price) {
       this.product = product;
       this.name = name;
       this.productName = productName;
       this.address = address;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Integer getIdObat() {
        return this.idObat;
    }
    
    public void setIdObat(Integer idObat) {
        this.idObat = idObat;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }

    public void addOrders(){
        System.out.println("id obat" + idObat);
        DAOOrders daoOrders = new DAOOrders();
        daoOrders.addOrders(this);
    }

    

}


