package com.model.pojo;
// Generated Oct 17, 2020 10:58:01 PM by Hibernate Tools 4.3.1

import com.DAO.DAOLogin;
import java.util.List;
import javax.faces.bean.ManagedBean;


@ManagedBean

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;

    public Users() {
    }

    public Users(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    public String validasiLogin(){
        DAOLogin uDao = new DAOLogin();
        List<Users> us = uDao.getBy(username, password);
        if (us != null){
            username = us.get(0).username;
            password = us.get(0).password;
            id = us.get(0).id;
            return "admin.xhtml";
        }
        return "error";
    }
    
    public void signup(){
        DAOLogin uDao = new DAOLogin();
        uDao.signUp(this);
        System.out.println("called");
    }
}